pipeline { 
    agent any
    tools{ 
        maven 'maven 3.9.8'
    }
    stages{ 
        stage("build"){
                when{ 
                    changeset "**/worker/**" 
                 } 
            steps{ 
                echo 'Compiling worker app' 
                dir('worker'){ 
                sh 'mvn compile' 
                } 
            } 
        } 
        stage("test"){
            when{ 
                changeset "**/worker/**"
            } 
            steps{ 
                echo 'Running Unit Tests on worker app'
                dir('worker'){
                    sh 'mvn clean test'
                }
            }            
        } 
        stage("package"){
            when{
                branch 'master' 
                changeset "**/worker/**" 
            } 
            steps{ 
                echo 'Packaging worker app'
                dir('worker'){
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: '**/target/*.jar',
fingerprint: true }

            }   
        }
    }
    post{ 
        always{
            echo 'Building multibranch pipeline for worker is completed..' 
        }
	failure{
	   slackSend (channel: "instavote-cd", message: "BuildFailed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)") }  
	s uccess{
	   slackSend (channel: "instavote-cd", message: "BuildSucceeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
	}
    } 
}
